cloud:
  compatibility-verifier:
    enabled: false
boot:
  admin:
    client:
      uri: http://localhost:1111/
spring:
  application:
    name: WELCOME_API_CONFIG 
spring:
  application:
    name: WELCOME_API_CONFIG1 

    
